version: "3"

services:
  db:
    image: postgres:15
    container_name: companyfactsDB
    environment:
      POSTGRES_DB: companydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./company_dump.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  fastapi:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: stockfinanceAPI
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
    environment:
      DB_NAME: companydb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    
networks:
  backend: