version: "3"

services:
  db:
    image: postgres:15
    container_name: companyfactsDB
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./company_dump.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  fastapi:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: stockfinanceAPI
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    
networks:
  backend: